language: generic

matrix:
  include:
    - os: linux
      env: CXX=g++-8 TARGET=test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

    - os: linux
      env: CXX=clang++-7 TARGET=test
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - g++-8 # libstdc++ but why!?
            - clang-7

    - os: linux
      env: CXX=g++-8 CXXFLAGS=--coverage TARGET=test-cxon
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - lcov-1.13
      after_success:
            - lcov --version
            - apt-cache search lcov
            - lcov --gcov-tool gcov-8 -c -d . -o cov.info
            - lcov -r cov.info '/usr/*' -o cov.info
            - lcov -l cov.info
            - bash <(curl -s https://codecov.io/bash) -f cov.info || echo "Codecov did not collect coverage reports"

script:
  - make $TARGET
