language: generic

matrix:
  include:
    - os: linux
      env: CXX=g++-8 TARGET=test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

    - os: linux
      env: CXX=clang++-7 TARGET=test
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - g++-8 # libstdc++ but why!?
            - clang-7

script:
  - make $TARGET
