language: generic

matrix:
  include:
    - os: linux
      env: CXX=g++-5 TARGET=test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - os: linux
      env: CXX=g++-8 TARGET=test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

    - os: linux
      env: CXX=clang++-3.5 TARGET=test
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - clang-3.5

    - os: linux
      env: CXX=clang++-8 TARGET=test
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - clang-8

    - os: linux
      env: CXX=g++-8 CXXFLAGS=--coverage TARGET=test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      after_success:
            - wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
            - tar xvfz lcov-1.14.tar.gz
            - make -C lcov-1.14
            - lcov-1.14/bin/lcov --gcov-tool gcov-8 -c -d . -o cov.info
            - lcov-1.14/bin/lcov -e cov.info '*/cxon/*.hxx' -o cxon.info 
            - lcov-1.14/bin/lcov -l cxon.info
            - bash <(curl -s https://codecov.io/bash) -f cxon.info || echo "upload failed"

    - os: windows
      language: bash
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
      script:
        - export PATH=$CMAKE_PATH:$PATH
        - mkdir .bld && cd .bld
        - cmake ..
        - cmake --build . -- config Release
        - ctest -V

script:
  - make $TARGET
