name: Codacy

on: [ push, pull_request, workflow_dispatch ]

jobs:
  codecov:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout boost/container
      uses: actions/checkout@v2
      with:
        repository: boostorg/container
        ref: master
        path: .dep/boost
    - name: Compiler setup
      run: sudo apt update; sudo apt install gcc-8 g++-8
    - name: Check
      env:
        CXX: g++-8
        CXXFLAGS: --coverage -O0 -std=c++17 -I ../.dep/boost/include
      run: |
        make -j check
        make -j time
    - name: LCOV setup
      run: |
        wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
        tar xvfz lcov-1.14.tar.gz
        make -C lcov-1.14
    - name: Coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        lcov-1.14/bin/lcov --gcov-tool gcov-8 -c -d . -o cov.info
        lcov-1.14/bin/lcov -e cov.info '*/cxon/*.hxx' -o cxon.info
        lcov-1.14/bin/lcov -l cxon.info
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l CPP -r cxon.info || echo "upload failed"
