name: Codacy

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '37 3 * * 6'

jobs:
  codecov:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v4
    - name: Compiler setup
      run: sudo apt update; sudo apt install gcc-8 g++-8
    - name: Checkout Boost
      uses: actions/checkout@v4
      with:
        repository: boostorg/boost
        ref: boost-1.81.0
        path: .dep/boost
    - name: Setup Boost
      run: |
        cd .dep/boost
        git submodule update --init tools/build
        git submodule update --init tools/boostdep
        git submodule update --init libs/config
        git submodule update --init libs/container
        python tools/boostdep/depinst/depinst.py container
        git submodule update --init libs/dynamic_bitset
        python tools/boostdep/depinst/depinst.py dynamic_bitset
        ./bootstrap.sh
        ./b2 headers
    - name: Check
      env:
        CXX: g++-8
        CXXFLAGS: --coverage -O0 -std=c++17 -I ../.dep/boost
      run: |
        make -j check
        make -j time
    - name: LCOV setup
      run: |
        wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
        tar xvfz lcov-1.14.tar.gz
        make -C lcov-1.14
    - name: Coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        lcov-1.14/bin/lcov --gcov-tool gcov-8 -c -d . -o cov.info
        lcov-1.14/bin/lcov -e cov.info '*/cxon/*.hxx' -o cxon.info
        lcov-1.14/bin/lcov -l cxon.info
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l CPP -r cxon.info || echo "upload failed"
