name: Coverity

on:
  workflow_dispatch:
  schedule:
    - cron: '58 23 * * 5'

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Coverity
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      run: |
        wget -q https://scan.coverity.com/download/linux64 --post-data "token=$TOKEN&project=oknenavin%2Fcxon" -O coverity-tool.tgz
        mkdir coverity-tool
        tar xzf coverity-tool.tgz --strip 1 -C coverity-tool
    - name: Build
      env:
        CXXFLAGS: -std=c++17
      run: |
        export PATH=`pwd`/coverity-tool/bin:$PATH
        cov-build --dir cov-int make -j
    - name: Submit
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
        MAIL: ${{ secrets.CXON_MAIL }}
      run: |
        tar czvf cxon.tgz cov-int
        curl \
          --form token=$TOKEN \
          --form email=$MAIL \
          --form file=@cxon.tgz \
          --form version="Current" \
          --form description="Current Branch" \
          https://scan.coverity.com/builds?project=oknenavin%2Fcxon
