name: macOS

on: [ push, pull_request, workflow_dispatch ]

jobs:
  xcode:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Boost
      uses: actions/checkout@v2
      with:
        repository: boostorg/boost
        ref: master
        path: .dep/boost
        submodules: recursive
    - name: Setup Boost
      run: |
        cd .dep/boost
        ./bootstrap.sh
        ./b2 headers
    - name: Configure
      run: |
        cd test
        cmake -S . -B .bld -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_FLAGS="-I ../../.dep/boost"
    - name: Build
      run: |
        cd test
        cmake --build .bld --parallel
    - name: Check
      run: |
        cd test/.bld
        ctest -j -V -C Release
