name: macOS

on: [ push, pull_request, workflow_dispatch ]

jobs:
  
  # xcode ######################################################################
    
  xcode:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: cd test ; cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
    - name: Build
      run: cd test ; cmake --build build --parallel
    - name: Check
      run: cd test/build ; ctest -j -V -C Release
