name: C/C++ CI

on:
  push:
    branches: [ features/cbor ]
  pull_request:
    branches: [ features/cbor ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make check
      run: make -j check
    #- name: make distcheck
    #  run: make distcheck
