name: C/C++ CI

on:
  push:
    branches: [ features/cbor ]
  pull_request:
    branches: [ features/cbor ]
  workflow_dispatch:
    branches: [ features/cbor ]

jobs:

  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make check
      run: make -j check
    #- name: make distcheck
    #  run: make distcheck

  clang-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install clang-10
      run: |
        sudo apt update
        sudo apt install clang-10
    - name: make check
      env:
        CXX: clang++-10
      run: make -j check
