name: Time

on: [ push, pull_request, workflow_dispatch ]

jobs:

  # gcc ########################################################################

  gcc-5:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-5 g++-5
    - name: Time
      env:
        CXX: g++-5
        CXXFLAGS: -std=c++11
      run: make time
    - name: Check Boost
      run: sudo apt-get update -y && apt-cache search ^libboost1

  gcc-10:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-10 g++-10
    - name: Time
      env:
        CXX: g++-10
        CXXFLAGS: -std=c++20
      run: make time
    - name: Check Boost
      run: sudo apt-get update -y && apt-cache search ^libboost1

  # clang ######################################################################

  clang-3-5:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install clang-3.5
    - name: Time
      env:
        CXX: clang++-3.5
        CXXFLAGS: -std=c++11
      run: make time
    - name: Check Boost
      run: sudo apt-get update -y && apt-cache search ^libboost1

  clang-11:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install clang-11
    - name: Time
      env:
        CXX: clang++-11
        CXXFLAGS: -std=c++20
      run: make time
    - name: Check Boost
      run: sudo apt-get update -y && apt-cache search ^libboost1
