name: Time

on: [ push, pull_request, workflow_dispatch ]

jobs:

  # gcc ########################################################################

  gcc-5:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-5 g++-5
    - name: Time
      env:
        CXX: g++-5
        CXXFLAGS: -DTIME_ONLY -std=c++11
      run: make time

  gcc-10:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Boost/JSON
      uses: actions/checkout@v1
      with:
        repository: boostorg/json
        ref: master
        path: boost.json
    - name: Checkout RapidJSON
      uses: actions/checkout@v1
      with:
        repository: tencent/rapidjson
        ref: master
        path: rapidjson
    - name: Checkout nlohmann/json
      uses: actions/checkout@v1
      with:
        repository: nlohmann/json
        ref: master
        path: nlohmann.json
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-10 g++-10
    - name: Time
      env:
        CXX: g++-10
        CXXFLAGS: -I ../../boost.json/include -I ../../rapidjson/include -I ../../nlohmann.json/single_include -DTIME_ONLY -DCOMPARE_WITH_BOOST_JSON -DCOMPARE_WITH_RAPIDJSON -DCOMPARE_WITH_NLOHMANN -std=c++20
      run: make time

  gcc-11:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Boost/JSON
      uses: actions/checkout@v1
      with:
        repository: boostorg/json
        ref: master
        path: boost.json
    - name: Checkout RapidJSON
      uses: actions/checkout@v1
      with:
        repository: tencent/rapidjson
        ref: master
        path: rapidjson
    - name: Checkout nlohmann/json
      uses: actions/checkout@v1
      with:
        repository: nlohmann/json
        ref: master
        path: nlohmann.json
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-11 g++-11
    - name: Time
      env:
        CXX: g++-11
        CXXFLAGS: -I ../../boost.json/include -I ../../rapidjson/include -I ../../nlohmann.json/single_include -DTIME_ONLY -DCOMPARE_WITH_BOOST_JSON -DCOMPARE_WITH_RAPIDJSON -DCOMPARE_WITH_NLOHMANN -std=c++20
      run: make time

  # clang ######################################################################

  #clang-3-5:
  #  runs-on: ubuntu-16.04
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Compiler setup
  #    run: |
  #      sudo apt-get update
  #      sudo apt-get install clang-3.5
  #  - name: Time
  #    env:
  #      CXX: clang++-3.5
  #      CXXFLAGS: -DTIME_ONLY -std=c++11
  #    run: make time

  clang-4:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install clang-4.0
    - name: Time
      env:
        CXX: clang++-4.0
        CXXFLAGS: -DTIME_ONLY -std=c++11
      run: make time

  clang-12:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Boost/JSON
      uses: actions/checkout@v1
      with:
        repository: boostorg/json
        ref: master
        path: boost.json
    - name: Checkout RapidJSON
      uses: actions/checkout@v1
      with:
        repository: tencent/rapidjson
        ref: master
        path: rapidjson
    - name: Checkout nlohmann/json
      uses: actions/checkout@v1
      with:
        repository: nlohmann/json
        ref: master
        path: nlohmann.json
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install clang-12
    - name: Time
      env:
        CXX: clang++-12
        CXXFLAGS: -I ../../boost.json/include -I ../../rapidjson/include -I ../../nlohmann.json/single_include -DTIME_ONLY -DCOMPARE_WITH_BOOST_JSON -DCOMPARE_WITH_RAPIDJSON -DCOMPARE_WITH_NLOHMANN -std=c++20
      run: make time
