name: Time

on: [ push, pull_request, workflow_dispatch ]

jobs:

  # gcc ########################################################################

  gcc-5:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-5 g++-5
    - name: Time
      env:
        CXX: g++-5
        CXXFLAGS: -std=c++11 -DCXON_TIME_ONLY
      run: make time

  gcc-11:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Boost/JSON
      uses: actions/checkout@v1
      with:
        repository: boostorg/json
        ref: master
        path: boost.json
    - name: Checkout RapidJSON
      uses: actions/checkout@v1
      with:
        repository: tencent/rapidjson
        ref: master
        path: rapidjson
    - name: Checkout nlohmann/json
      uses: actions/checkout@v1
      with:
        repository: nlohmann/json
        ref: master
        path: nlohmann.json
    - name: Checkout fastfloat/fast_float
      uses: actions/checkout@v1
      with:
        repository: fastfloat/fast_float
        ref: main
        path: fast_float
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-11 g++-11
    - name: Prepare the storage
      run: git clone https://github.com/oknenavin/store.git ../store
    - name: Time
      env:
        CXX: g++-11
        CXXFLAGS: -std=c++20 -DCXON_TIME_ONLY -I ../../boost.json/include -DCXON_TIME_BOOST_JSON -I ../../rapidjson/include -DCXON_TIME_RAPIDJSON -I ../../nlohmann.json/single_include -DCXON_TIME_NLOHMANN
      run: |
        echo "$(date -u --iso-8601=seconds) / g++11 / defualt" >> ../store/cxon/benchmarks/tables.txt
        make -s time | tee -a ../store/cxon/benchmarks/tables.txt
        printf "\n"
    - name: Time (fast_float)
      env:
        CXX: g++-11
        CXXFLAGS: -std=c++20 -DCXON_TIME_ONLY -I ../../fast_float/include -DCXON_TIME_FAST_FLOAT -I ../../boost.json/include -DCXON_TIME_BOOST_JSON -I ../../rapidjson/include -DCXON_TIME_RAPIDJSON -I ../../nlohmann.json/single_include -DCXON_TIME_NLOHMANN
      run: |
        echo "$(date -u --iso-8601=seconds) / g++11 / fast_float" >> ../store/cxon/benchmarks/tables.txt
        make -s clean && make -s time | tee -a ../store/cxon/benchmarks/tables.txt
        printf "\n"
    - name: Store the results
      run: |
        cd ../store
        git config user.email "oknenavin@outlook.com"
        git config user.name "oknenavin"
        git commit -am "$(date -u --iso-8601=seconds)"
        git push 

  # clang ######################################################################

  #clang-3-5:
  #  runs-on: ubuntu-16.04
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Compiler setup
  #    run: |
  #      sudo apt-get update
  #      sudo apt-get install clang-3.5
  #  - name: Time
  #    env:
  #      CXX: clang++-3.5
  #      CXXFLAGS: -std=c++11 -DCXON_TIME_ONLY
  #    run: make time

  clang-4:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install clang-4.0
    - name: Time
      env:
        CXX: clang++-4.0
        CXXFLAGS: -std=c++11 -DCXON_TIME_ONLY
      run: make time

  clang-12:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Boost/JSON
      uses: actions/checkout@v1
      with:
        repository: boostorg/json
        ref: master
        path: boost.json
    - name: Checkout RapidJSON
      uses: actions/checkout@v1
      with:
        repository: tencent/rapidjson
        ref: master
        path: rapidjson
    - name: Checkout nlohmann/json
      uses: actions/checkout@v1
      with:
        repository: nlohmann/json
        ref: master
        path: nlohmann.json
    - name: Checkout fastfloat/fast_float
      uses: actions/checkout@v1
      with:
        repository: fastfloat/fast_float
        ref: main
        path: fast_float
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install clang-12
    - name: Time
      env:
        CXX: clang++-12
        CXXFLAGS: -std=c++20 -DCXON_TIME_ONLY -I ../../boost.json/include -DCXON_TIME_BOOST_JSON -I ../../rapidjson/include -DCXON_TIME_RAPIDJSON -I ../../nlohmann.json/single_include -DCXON_TIME_NLOHMANN
      run: make time
    - name: Time (fast_float)
      env:
        CXX: clang++-12
        CXXFLAGS: -std=c++20 -DCXON_TIME_ONLY -I ../../fast_float/include -DCXON_TIME_FAST_FLOAT -I ../../boost.json/include -DCXON_TIME_BOOST_JSON -I ../../rapidjson/include -DCXON_TIME_RAPIDJSON -I ../../nlohmann.json/single_include -DCXON_TIME_NLOHMANN
      run: make clean && make time
