name: Windows

on: [ push, pull_request, workflow_dispatch ]

jobs:
  msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Boost
      uses: actions/checkout@v2
      with:
        repository: boostorg/boost
        ref: master
        path: .dep/boost
    - name: Setup Boost
      shell: bash
      run: |
        cd .dep/boost
        git submodule update --init tools/build
        git submodule update --init tools/boostdep
        git submodule update --init libs/config
        git submodule update --init libs/container
        python tools/boostdep/depinst/depinst.py container
        ./bootstrap.sh
        ./b2 headers
    - name: Configure
      run: |
        cd test
        cmake -S . -B .bld -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_STANDARD=17 -D CMAKE_CXX_FLAGS="/I ../../.dep/boost"
    - name: Build
      run: |
        cd test
        cmake --build .bld --config Release --parallel
    - name: Check
      run: |
        cd test/.bld
        ctest -j -V -C Release
