name: Windows

on: [ push, pull_request, workflow_dispatch ]

jobs:
  
  # msvc #######################################################################
    
  msvc-2019:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cd test ; cmake -S . -B build -G "Visual Studio 16 2019" -D CMAKE_BUILD_TYPE=Debug
    - name: build
      run: cmake --build build --parallel
    - name: test
      run: cd build ; ctest -j -V -C Debug --output-on-failure
